# Python IO Advanced

## Python & RE (regex)
Using regular expression with Python

## Python & MarkUpText (html, xml)
std lib xml.

## HDF5
https://www.hdfgroup.org/

## Advanced for Matplotlib
OOP operation of Matplotlib

# **The documentation is not finished yet.**

## Python & RE (regex)
Using regular expression with Python

some tutorial

https://www.tutorialspoint.com/python/python_reg_expressions.htm

See the RE folder.

In [27]:
import re

re.match(pattern, string, flags=0)

In [29]:
print(re.match('www', 'www.github.com').span())

(0, 3)


In [30]:
print(re.match('com', 'www.github.com'))

None


In [31]:
line = "Cats are smarter than dogs"
 
matchObj = re.match( r'(.*) are (.*?) .*', line, re.M|re.I)

if matchObj:
   print("matchObj.group() : ", matchObj.group())
   print("matchObj.group(1) : ", matchObj.group(1))
   print("matchObj.group(2) : ", matchObj.group(2))
else:
   print("No match!!")

matchObj.group() :  Cats are smarter than dogs
matchObj.group(1) :  Cats
matchObj.group(2) :  smarter


Raw string mark 'r'

https://docs.python.org/3.6/library/re.html#raw-string-notation

'u' for Unicode

'b' for Bytes

In [34]:
line = "Cats are smarter than dogs";

matchObj = re.match( r'dogs', line, re.M|re.I)
if matchObj:
   print("match --> matchObj.group() : ", matchObj.group())
else:
   print("No match!!")

searchObj = re.search( r'dogs', line, re.M|re.I)
if searchObj:
   print("search --> searchObj.group() : ", searchObj.group())
else:
   print("Nothing found!!")

No match!!
search --> searchObj.group() :  dogs


In [35]:
phone = "2004-959-559 # This is Phone Number"

# Delete Python-style comments
num = re.sub(r'#.*$', "", phone)
print("Phone Num : ", num)

# Remove anything other than digits
num = re.sub(r'\D', "", phone)    
print("Phone Num : ", num)

Phone Num :  2004-959-559 
Phone Num :  2004959559



## Python & MarkUpText (html, xml)
std lib xml.



See example in xml folder.

## HDF5

HDF stand for `Hierarchical Data Format`.

Home page: https://www.hdfgroup.org/

Official doc: http://docs.h5py.org/en/stable/high/file.html#opening-creating-files

Official guide: https://portal.hdfgroup.org/display/HDF5/HDF5+User%27s+Guide

Tutorial(Chinese): https://blog.csdn.net/yudf2010/article/details/50353292

In [1]:
import h5py

In [2]:
import numpy as np
f = h5py.File('./hdf5/myfile.hdf5','w')

In [3]:
dset = f.create_dataset("mydataset",(100,2),dtype='f')

In [4]:
arr = np.random.rand(100,2)
dset = f.create_dataset("init",data=arr)

In [5]:
g = h5py.File('./hdf5/myfile.hdf5','r')

In [6]:
print(g.keys())

KeysView(<HDF5 file "myfile.hdf5" (mode r+)>)


In [7]:
for key in f.keys():
    print(key)
    print(f[key].name)
    print(f[key].shape)
    print(f[key].value[0:5])
    

init
/init
(100, 2)
[[0.3135762  0.28650201]
 [0.16429446 0.42356342]
 [0.50942349 0.6801578 ]
 [0.86468874 0.58730587]
 [0.19549155 0.76929158]]
mydataset
/mydataset
(100, 2)
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [8]:
g.close()

In [9]:
f.close()

In [10]:
f = h5py.File('./hdf5/myfile.hdf5','r+')

In [11]:
for key in f.keys():
    print(key)

init
mydataset


In [12]:
data = f['mydataset']
data[...] = np.random.rand(100,2)

In [13]:
for key in f.keys():
    print(key)

init
mydataset


In [14]:
f['mydataset'][0:5]

array([[0.1757824 , 0.09998398],
       [0.63305527, 0.9996707 ],
       [0.83607554, 0.47740483],
       [0.6329356 , 0.7614831 ],
       [0.5598986 , 0.9395614 ]], dtype=float32)

In [15]:
f.close()

In [16]:
f = h5py.File('./hdf5/group.hdf5','w')
dset = f.create_dataset("autochunk",(100,100),chunks=True)
dset[0:10,:] = np.random.randint(0,10,size=(10,100))

In [17]:
dset[10:,:]=np.random.rand(90,100)

In [18]:
dset[0:20,:]

array([[0.        , 4.        , 1.        , ..., 7.        , 8.        ,
        8.        ],
       [2.        , 3.        , 2.        , ..., 9.        , 3.        ,
        1.        ],
       [1.        , 6.        , 9.        , ..., 1.        , 5.        ,
        5.        ],
       ...,
       [0.5224717 , 0.2337529 , 0.02856528, ..., 0.8768636 , 0.1099859 ,
        0.54242194],
       [0.14540748, 0.13466418, 0.80195594, ..., 0.23663245, 0.81982607,
        0.48894787],
       [0.08232588, 0.47629642, 0.59545565, ..., 0.18400279, 0.02850683,
        0.09432878]], dtype=float32)

In [19]:
dset[0:10,0:5]

array([[0., 4., 1., 8., 8.],
       [2., 3., 2., 1., 7.],
       [1., 6., 9., 2., 1.],
       [3., 8., 0., 7., 1.],
       [3., 1., 6., 8., 0.],
       [9., 6., 5., 0., 9.],
       [1., 8., 7., 0., 7.],
       [0., 4., 9., 1., 1.],
       [9., 6., 9., 7., 5.],
       [3., 2., 7., 1., 9.]], dtype=float32)

In [20]:
f.close()

In [21]:
f=h5py.File("myh5py.hdf5","w")

In [22]:
g1=f.create_group("bar")

In [23]:
g1["dset1"]=np.arange(10)
g1["dset2"]=np.arange(12).reshape((3,4))

In [24]:
for key in g1.keys():
    print(g1[key].name)
    print(g1[key].value)

/bar/dset1
[0 1 2 3 4 5 6 7 8 9]
/bar/dset2
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [25]:
f.visit(lambda x: print(x))

bar
bar/dset1
bar/dset2


In [26]:
f.close()

## Advanced for Matplotlib

Layer detail(Chinese) : https://blog.csdn.net/Xw_Classmate/article/details/51174921
